all:
	g++ -g controller.cxx Monitor.cxx Message.cxx MetricType.cxx Metric.cxx MetricHandler.cxx -Ilib -lmysqlclient -lmysqlpp -L/usr/lib64/mysql/ -I/usr/include/mysql -I/usr/include/mysql++ -o controller
