// systemtap health monitor
// Copyright (C) 2010 Aaron Luchko
//
// This file is part of systemtap, and is free software.  You can
// redistribute it and/or modify it under the terms of the GNU General
// Public License (GPL); either version 2, or (at your option) any
// later version.
#ifndef METRICTYPE_H
#define METRICTYPE_H 1

namespace systemtap
{
  class MetricType
  {
  private:
    int id;
    double min;
    bool minSet;
    double max;
    bool maxSet;
    double def;
    bool defSet;
    char* typeName;
  public:
    MetricType() {};
    // set the autogenerated id through a statement in the database
    void setId(int dbId);
    // This should be set to the primary key that was set by the database
    int getId();
    void setName(char* name);
    char* getName();
    void setMin(double min);
    double getMin();
    bool isMinSet();
    void setMax(double max);
    double getMax();
    bool isMaxSet();
    void setDefault(double value);
    double getDefault();
    bool isDefaultSet();
  };
}
#endif
